quarkus.mongodb.connection-string=mongodb://admin:adminpassword@localhost:27017/?authSource=admin

jnosql.document.database=javify_db

quarkus.http.port=8082

quarkus.mongodb.devservices.enabled=false
quarkus.redis.devservices.enabled=false

# adicionar a config para que o Quarkus carregue os componentes do Redis
quarkus.redis.hosts=redis://localhost:6379

# TTL Global (1 hora)
quarkus.cache.redis.expire-after-write=1h

# Para o cache "album" (detalhe)
quarkus.cache.redis.album.value-type=br.com.unipds.javify.catalogo.domain.Album

# Para o cache "albuns" (listagem/paginação)
quarkus.cache.redis.albuns.value-type=br.com.unipds.javify.catalogo.domain.PagedAlbumList